// Automatically generated by astro-icon
// b8b6c88cdeb1b7c4aaea2a0137f37f8f0b78314fe87b572f189e12a56f297a6b

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "icon--award"
		| "icon--css"
		| "icon--design"
		| "icon--dribbble"
		| "icon--github"
		| "icon--html"
		| "icon--instagram"
		| "icon--javascript"
		| "icon--react"
		| "icon--react-router"
		| "icon--speed"
		| "icon--tailwind"
		| "icon--twitter"
		| "icon--vite"
		| "icon--youtube"
		| "logomark";
}